export interface NonStationPlaceRow {
  place: string
  count: number
  pct_of_named_non_station: number
  pickup_count: number
  dropoff_count: number
}

export interface NonStationCategoryRow {
  category: string
  count: number
  pct_of_named_non_station: number
  pickup_count: number
  dropoff_count: number
}

export const nonStationSummary = {
  namedTotal: 615098,
  nonStationNamedTotal: 535348,
  nonStationRatioPct: 87.035,
  highFreqThreshold: 100,
  highFreqPlacesCount: 380,
} as const

export const nonStationHighFreqPlaces: NonStationPlaceRow[] = [
  {
    place: '住家',
    count: 81987,
    pct_of_named_non_station: 15.315,
    pickup_count: 81986,
    dropoff_count: 1,
  },
  {
    place: '公司',
    count: 29954,
    pct_of_named_non_station: 5.595,
    pickup_count: 29954,
    dropoff_count: 0,
  },
  {
    place: '家',
    count: 2562,
    pct_of_named_non_station: 0.479,
    pickup_count: 2562,
    dropoff_count: 0,
  },
  {
    place: 'Home',
    count: 1713,
    pct_of_named_non_station: 0.32,
    pickup_count: 1713,
    dropoff_count: 0,
  },
  {
    place: '台北101 yoxi上車點 松智路出口',
    count: 1425,
    pct_of_named_non_station: 0.266,
    pickup_count: 724,
    dropoff_count: 701,
  },
  {
    place: '台北市府路 yoxi上車點 門口右側黃線臨停區',
    count: 946,
    pct_of_named_non_station: 0.177,
    pickup_count: 795,
    dropoff_count: 151,
  },
  {
    place: '台安醫院',
    count: 892,
    pct_of_named_non_station: 0.167,
    pickup_count: 162,
    dropoff_count: 730,
  },
  {
    place: '晶華酒店',
    count: 838,
    pct_of_named_non_station: 0.157,
    pickup_count: 180,
    dropoff_count: 658,
  },
  {
    place: '台北馬偕醫院',
    count: 722,
    pct_of_named_non_station: 0.135,
    pickup_count: 40,
    dropoff_count: 682,
  },
  {
    place: '夢時代購物中心 yoxi上車點 時代大道',
    count: 692,
    pct_of_named_non_station: 0.129,
    pickup_count: 278,
    dropoff_count: 414,
  },
  {
    place: '衛生福利部雙和醫院',
    count: 677,
    pct_of_named_non_station: 0.126,
    pickup_count: 53,
    dropoff_count: 624,
  },
  {
    place: '亞東醫院',
    count: 670,
    pct_of_named_non_station: 0.125,
    pickup_count: 115,
    dropoff_count: 555,
  },
  {
    place: '漢神巨蛋購物廣場',
    count: 652,
    pct_of_named_non_station: 0.122,
    pickup_count: 38,
    dropoff_count: 614,
  },
  {
    place: '高雄萬豪酒店',
    count: 605,
    pct_of_named_non_station: 0.113,
    pickup_count: 197,
    dropoff_count: 408,
  },
  {
    place: '錢櫃KTV台北忠孝店',
    count: 603,
    pct_of_named_non_station: 0.113,
    pickup_count: 261,
    dropoff_count: 342,
  },
  {
    place: '新光三越台北信義新天地A11館',
    count: 593,
    pct_of_named_non_station: 0.111,
    pickup_count: 188,
    dropoff_count: 405,
  },
  {
    place: '遠東SOGO百貨忠孝館',
    count: 575,
    pct_of_named_non_station: 0.107,
    pickup_count: 76,
    dropoff_count: 499,
  },
  {
    place: '新光醫院',
    count: 561,
    pct_of_named_non_station: 0.105,
    pickup_count: 93,
    dropoff_count: 468,
  },
  {
    place: '台大醫院正門 yoxi上車點',
    count: 536,
    pct_of_named_non_station: 0.1,
    pickup_count: 378,
    dropoff_count: 158,
  },
  {
    place: '老虎城購物中心',
    count: 534,
    pct_of_named_non_station: 0.1,
    pickup_count: 227,
    dropoff_count: 307,
  },
  {
    place: '錢櫃KTV台北中華新館店',
    count: 528,
    pct_of_named_non_station: 0.099,
    pickup_count: 209,
    dropoff_count: 319,
  },
  {
    place: 'ATT 4 FUN',
    count: 521,
    pct_of_named_non_station: 0.097,
    pickup_count: 97,
    dropoff_count: 424,
  },
  {
    place: '台大醫院西址',
    count: 513,
    pct_of_named_non_station: 0.096,
    pickup_count: 25,
    dropoff_count: 488,
  },
  {
    place: 'W HOTEL',
    count: 499,
    pct_of_named_non_station: 0.093,
    pickup_count: 247,
    dropoff_count: 252,
  },
  {
    place: '新光三越台中中港店',
    count: 498,
    pct_of_named_non_station: 0.093,
    pickup_count: 32,
    dropoff_count: 466,
  },
  {
    place: '台北喜來登大飯店',
    count: 486,
    pct_of_named_non_station: 0.091,
    pickup_count: 156,
    dropoff_count: 330,
  },
  {
    place: '台中大遠百後門車道yoxi上車點 (市政北七路)',
    count: 482,
    pct_of_named_non_station: 0.09,
    pickup_count: 227,
    dropoff_count: 255,
  },
  {
    place: '遠東SOGO百貨復興館',
    count: 460,
    pct_of_named_non_station: 0.086,
    pickup_count: 24,
    dropoff_count: 436,
  },
  {
    place: '台北國泰醫院',
    count: 456,
    pct_of_named_non_station: 0.085,
    pickup_count: 43,
    dropoff_count: 413,
  },
  {
    place: '漢來大飯店',
    count: 455,
    pct_of_named_non_station: 0.085,
    pickup_count: 125,
    dropoff_count: 330,
  },
  {
    place: '第二醫療大樓門口-yoxi上車點',
    count: 451,
    pct_of_named_non_station: 0.084,
    pickup_count: 314,
    dropoff_count: 137,
  },
  {
    place: '錢櫃KTV台中自由店',
    count: 444,
    pct_of_named_non_station: 0.083,
    pickup_count: 180,
    dropoff_count: 264,
  },
  {
    place: '微風廣場本館',
    count: 434,
    pct_of_named_non_station: 0.081,
    pickup_count: 88,
    dropoff_count: 346,
  },
  {
    place: 'home',
    count: 434,
    pct_of_named_non_station: 0.081,
    pickup_count: 434,
    dropoff_count: 0,
  },
  {
    place: '京站時尚廣場',
    count: 433,
    pct_of_named_non_station: 0.081,
    pickup_count: 112,
    dropoff_count: 321,
  },
  {
    place: '台北市政府',
    count: 423,
    pct_of_named_non_station: 0.079,
    pickup_count: 47,
    dropoff_count: 376,
  },
  {
    place: '台北君悅酒店',
    count: 422,
    pct_of_named_non_station: 0.079,
    pickup_count: 102,
    dropoff_count: 320,
  },
  {
    place: '錢櫃KTV台北松江店',
    count: 418,
    pct_of_named_non_station: 0.078,
    pickup_count: 190,
    dropoff_count: 228,
  },
  {
    place: '中正樓-yoxi上車點',
    count: 413,
    pct_of_named_non_station: 0.077,
    pickup_count: 326,
    dropoff_count: 87,
  },
  {
    place: '萬芳醫院',
    count: 411,
    pct_of_named_non_station: 0.077,
    pickup_count: 103,
    dropoff_count: 308,
  },
  {
    place: '台大醫學院附設癌醫中心醫院',
    count: 409,
    pct_of_named_non_station: 0.076,
    pickup_count: 54,
    dropoff_count: 355,
  },
  {
    place: '台大醫院東址',
    count: 400,
    pct_of_named_non_station: 0.075,
    pickup_count: 34,
    dropoff_count: 366,
  },
  {
    place: '新光三越高雄左營店彩虹市集',
    count: 400,
    pct_of_named_non_station: 0.075,
    pickup_count: 180,
    dropoff_count: 220,
  },
  {
    place: '環球購物中心中和店',
    count: 396,
    pct_of_named_non_station: 0.074,
    pickup_count: 62,
    dropoff_count: 334,
  },
  {
    place: '台大兒童醫院',
    count: 395,
    pct_of_named_non_station: 0.074,
    pickup_count: 75,
    dropoff_count: 320,
  },
  {
    place: '高醫大附設中和紀念醫院',
    count: 393,
    pct_of_named_non_station: 0.073,
    pickup_count: 32,
    dropoff_count: 361,
  },
  {
    place: '微風廣場南山館',
    count: 391,
    pct_of_named_non_station: 0.073,
    pickup_count: 33,
    dropoff_count: 358,
  },
  {
    place: '新光三越中港店 yoxi 上車點 後門車道(市政北七路)',
    count: 390,
    pct_of_named_non_station: 0.073,
    pickup_count: 302,
    dropoff_count: 88,
  },
  {
    place: '松山文創園區誠品行旅 yoxi上車點',
    count: 379,
    pct_of_named_non_station: 0.071,
    pickup_count: 317,
    dropoff_count: 62,
  },
  {
    place: '內湖三總',
    count: 377,
    pct_of_named_non_station: 0.07,
    pickup_count: 37,
    dropoff_count: 340,
  },
  {
    place: '漢神百貨',
    count: 375,
    pct_of_named_non_station: 0.07,
    pickup_count: 69,
    dropoff_count: 306,
  },
  {
    place: '新光三越台北信義新天地A8館',
    count: 375,
    pct_of_named_non_station: 0.07,
    pickup_count: 93,
    dropoff_count: 282,
  },
  {
    place: '台北信義威秀影城',
    count: 370,
    pct_of_named_non_station: 0.069,
    pickup_count: 35,
    dropoff_count: 335,
  },
  {
    place: '台北小巨蛋',
    count: 368,
    pct_of_named_non_station: 0.069,
    pickup_count: 7,
    dropoff_count: 361,
  },
  {
    place: '遠東百貨遠百信義A13店',
    count: 368,
    pct_of_named_non_station: 0.069,
    pickup_count: 42,
    dropoff_count: 326,
  },
  {
    place: '微風廣場南京館',
    count: 365,
    pct_of_named_non_station: 0.068,
    pickup_count: 108,
    dropoff_count: 257,
  },
  {
    place: '錢櫃KTV高雄中華新館店',
    count: 363,
    pct_of_named_non_station: 0.068,
    pickup_count: 123,
    dropoff_count: 240,
  },
  {
    place: '台北101',
    count: 359,
    pct_of_named_non_station: 0.067,
    pickup_count: 7,
    dropoff_count: 352,
  },
  {
    place: '大巨蛋-yoxi上車點-光復南路側小客車臨停區',
    count: 351,
    pct_of_named_non_station: 0.066,
    pickup_count: 138,
    dropoff_count: 213,
  },
  {
    place: '台北101 yoxi上車點 市府路出口',
    count: 343,
    pct_of_named_non_station: 0.064,
    pickup_count: 203,
    dropoff_count: 140,
  },
  {
    place: '台北行天宮',
    count: 339,
    pct_of_named_non_station: 0.063,
    pickup_count: 7,
    dropoff_count: 332,
  },
  {
    place: '三軍總醫院內湖院區',
    count: 334,
    pct_of_named_non_station: 0.062,
    pickup_count: 25,
    dropoff_count: 309,
  },
  {
    place: 'H',
    count: 332,
    pct_of_named_non_station: 0.062,
    pickup_count: 332,
    dropoff_count: 0,
  },
  {
    place: '台北寒舍艾美酒店',
    count: 332,
    pct_of_named_non_station: 0.062,
    pickup_count: 119,
    dropoff_count: 213,
  },
  {
    place: '巷口',
    count: 328,
    pct_of_named_non_station: 0.061,
    pickup_count: 328,
    dropoff_count: 0,
  },
  {
    place: '台北漢來大飯店',
    count: 325,
    pct_of_named_non_station: 0.061,
    pickup_count: 120,
    dropoff_count: 205,
  },
  {
    place: '7-11',
    count: 322,
    pct_of_named_non_station: 0.06,
    pickup_count: 322,
    dropoff_count: 0,
  },
  {
    place: '台北市立聯合醫院仁愛醫院',
    count: 320,
    pct_of_named_non_station: 0.06,
    pickup_count: 23,
    dropoff_count: 297,
  },
  {
    place: '南港Lalaport - yoxi上車點',
    count: 320,
    pct_of_named_non_station: 0.06,
    pickup_count: 219,
    dropoff_count: 101,
  },
  {
    place: '天成大飯店',
    count: 317,
    pct_of_named_non_station: 0.059,
    pickup_count: 203,
    dropoff_count: 114,
  },
  {
    place: '台北美福大飯店',
    count: 315,
    pct_of_named_non_station: 0.059,
    pickup_count: 97,
    dropoff_count: 218,
  },
  {
    place: '高雄市衛生局',
    count: 315,
    pct_of_named_non_station: 0.059,
    pickup_count: 69,
    dropoff_count: 246,
  },
  {
    place: '台北萬豪酒店',
    count: 309,
    pct_of_named_non_station: 0.058,
    pickup_count: 42,
    dropoff_count: 267,
  },
  {
    place: '新光三越台南新天地本館',
    count: 305,
    pct_of_named_non_station: 0.057,
    pickup_count: 112,
    dropoff_count: 193,
  },
  {
    place: '宏匯廣場',
    count: 303,
    pct_of_named_non_station: 0.057,
    pickup_count: 72,
    dropoff_count: 231,
  },
  {
    place: '台北家',
    count: 302,
    pct_of_named_non_station: 0.056,
    pickup_count: 302,
    dropoff_count: 0,
  },
  {
    place: '上車',
    count: 300,
    pct_of_named_non_station: 0.056,
    pickup_count: 300,
    dropoff_count: 0,
  },
  {
    place: '1',
    count: 299,
    pct_of_named_non_station: 0.056,
    pickup_count: 299,
    dropoff_count: 0,
  },
  {
    place: '上班',
    count: 297,
    pct_of_named_non_station: 0.055,
    pickup_count: 297,
    dropoff_count: 0,
  },
  {
    place: '華山1914文化創意產業園區',
    count: 296,
    pct_of_named_non_station: 0.055,
    pickup_count: 17,
    dropoff_count: 279,
  },
  {
    place: '台北世貿中心展覽一館',
    count: 295,
    pct_of_named_non_station: 0.055,
    pickup_count: 40,
    dropoff_count: 255,
  },
  {
    place: '裕隆城',
    count: 295,
    pct_of_named_non_station: 0.055,
    pickup_count: 53,
    dropoff_count: 242,
  },
  {
    place: '台北第二殯儀館',
    count: 294,
    pct_of_named_non_station: 0.055,
    pickup_count: 23,
    dropoff_count: 271,
  },
  {
    place: '新光三越台北南西店一館',
    count: 293,
    pct_of_named_non_station: 0.055,
    pickup_count: 49,
    dropoff_count: 244,
  },
  {
    place: '典華大直旗艦館',
    count: 291,
    pct_of_named_non_station: 0.054,
    pickup_count: 65,
    dropoff_count: 226,
  },
  {
    place: '新家',
    count: 288,
    pct_of_named_non_station: 0.054,
    pickup_count: 288,
    dropoff_count: 0,
  },
  {
    place: '遠東百貨高雄大遠百店',
    count: 285,
    pct_of_named_non_station: 0.053,
    pickup_count: 51,
    dropoff_count: 234,
  },
  {
    place: '微風廣場信義館',
    count: 285,
    pct_of_named_non_station: 0.053,
    pickup_count: 46,
    dropoff_count: 239,
  },
  {
    place: '馬偕醫院門口黃線處-yoxi上車點',
    count: 284,
    pct_of_named_non_station: 0.053,
    pickup_count: 229,
    dropoff_count: 55,
  },
  {
    place: '台北國泰萬怡酒店',
    count: 280,
    pct_of_named_non_station: 0.052,
    pickup_count: 116,
    dropoff_count: 164,
  },
  {
    place: 'Work',
    count: 277,
    pct_of_named_non_station: 0.052,
    pickup_count: 277,
    dropoff_count: 0,
  },
  {
    place: '慈濟醫院台北分院',
    count: 272,
    pct_of_named_non_station: 0.051,
    pickup_count: 62,
    dropoff_count: 210,
  },
  {
    place: '台北文華東方酒店',
    count: 267,
    pct_of_named_non_station: 0.05,
    pickup_count: 53,
    dropoff_count: 214,
  },
  {
    place: '上車點',
    count: 265,
    pct_of_named_non_station: 0.05,
    pickup_count: 265,
    dropoff_count: 0,
  },
  {
    place: '國泰綜合醫院台北總院',
    count: 265,
    pct_of_named_non_station: 0.05,
    pickup_count: 52,
    dropoff_count: 213,
  },
  {
    place: '享溫馨庭園式自助KTV建國店',
    count: 262,
    pct_of_named_non_station: 0.049,
    pickup_count: 94,
    dropoff_count: 168,
  },
  {
    place: '台積電晶圓22廠',
    count: 258,
    pct_of_named_non_station: 0.048,
    pickup_count: 30,
    dropoff_count: 228,
  },
  {
    place: '明曜百貨',
    count: 254,
    pct_of_named_non_station: 0.047,
    pickup_count: 51,
    dropoff_count: 203,
  },
  {
    place: '板橋大遠百',
    count: 253,
    pct_of_named_non_station: 0.047,
    pickup_count: 43,
    dropoff_count: 210,
  },
  {
    place: '新光三越台北信義新天地A9館',
    count: 252,
    pct_of_named_non_station: 0.047,
    pickup_count: 40,
    dropoff_count: 212,
  },
  {
    place: '台北圓山大飯店',
    count: 251,
    pct_of_named_non_station: 0.047,
    pickup_count: 50,
    dropoff_count: 201,
  },
  {
    place: '振興醫院',
    count: 250,
    pct_of_named_non_station: 0.047,
    pickup_count: 41,
    dropoff_count: 209,
  },
  {
    place: '中友百貨公司',
    count: 249,
    pct_of_named_non_station: 0.047,
    pickup_count: 33,
    dropoff_count: 216,
  },
  {
    place: '誠品生活南西店',
    count: 248,
    pct_of_named_non_station: 0.046,
    pickup_count: 70,
    dropoff_count: 178,
  },
  {
    place: '超級巨星自助式KTV市政河南店',
    count: 246,
    pct_of_named_non_station: 0.046,
    pickup_count: 111,
    dropoff_count: 135,
  },
  {
    place: '住家2',
    count: 245,
    pct_of_named_non_station: 0.046,
    pickup_count: 245,
    dropoff_count: 0,
  },
  {
    place: '漢來巨蛋 yoxi上車點 接送區',
    count: 242,
    pct_of_named_non_station: 0.045,
    pickup_count: 206,
    dropoff_count: 36,
  },
  {
    place: '輔大醫院',
    count: 238,
    pct_of_named_non_station: 0.044,
    pickup_count: 31,
    dropoff_count: 207,
  },
  {
    place: '新光三越台北南西店三館',
    count: 235,
    pct_of_named_non_station: 0.044,
    pickup_count: 26,
    dropoff_count: 209,
  },
  {
    place: '星聚點台北旗艦館',
    count: 235,
    pct_of_named_non_station: 0.044,
    pickup_count: 78,
    dropoff_count: 157,
  },
  {
    place: '成大醫院 yoxi上車點 門診大樓門口上車',
    count: 235,
    pct_of_named_non_station: 0.044,
    pickup_count: 157,
    dropoff_count: 78,
  },
  {
    place: 'MITSUI SHOPPING PARK LALAPORT南港館',
    count: 233,
    pct_of_named_non_station: 0.044,
    pickup_count: 11,
    dropoff_count: 222,
  },
  {
    place: '三創生活園區',
    count: 233,
    pct_of_named_non_station: 0.044,
    pickup_count: 32,
    dropoff_count: 201,
  },
  {
    place: '長庚醫院高雄分院-兒童大樓',
    count: 233,
    pct_of_named_non_station: 0.044,
    pickup_count: 79,
    dropoff_count: 154,
  },
  {
    place: '高雄福華大飯店',
    count: 232,
    pct_of_named_non_station: 0.043,
    pickup_count: 53,
    dropoff_count: 179,
  },
  {
    place: '台北醫學大學附設醫院',
    count: 230,
    pct_of_named_non_station: 0.043,
    pickup_count: 7,
    dropoff_count: 223,
  },
  {
    place: '錢櫃KTV台北林森店',
    count: 227,
    pct_of_named_non_station: 0.042,
    pickup_count: 94,
    dropoff_count: 133,
  },
  {
    place: '娘家',
    count: 226,
    pct_of_named_non_station: 0.042,
    pickup_count: 226,
    dropoff_count: 0,
  },
  {
    place: '成大 yoxi上車點 住院大樓門口上車',
    count: 225,
    pct_of_named_non_station: 0.042,
    pickup_count: 154,
    dropoff_count: 71,
  },
  {
    place: '高雄日航酒店',
    count: 224,
    pct_of_named_non_station: 0.042,
    pickup_count: 63,
    dropoff_count: 161,
  },
  {
    place: '台南看守所',
    count: 223,
    pct_of_named_non_station: 0.042,
    pickup_count: 65,
    dropoff_count: 158,
  },
  {
    place: '奇美醫院永康分院',
    count: 223,
    pct_of_named_non_station: 0.042,
    pickup_count: 36,
    dropoff_count: 187,
  },
  {
    place: '萬豪酒店 yoxi上車點 敬業四路出口',
    count: 221,
    pct_of_named_non_station: 0.041,
    pickup_count: 157,
    dropoff_count: 64,
  },
  {
    place: '大同醫院',
    count: 220,
    pct_of_named_non_station: 0.041,
    pickup_count: 68,
    dropoff_count: 152,
  },
  {
    place: '國泰置地廣場',
    count: 219,
    pct_of_named_non_station: 0.041,
    pickup_count: 56,
    dropoff_count: 163,
  },
  {
    place: '義享時尚廣場',
    count: 218,
    pct_of_named_non_station: 0.041,
    pickup_count: 33,
    dropoff_count: 185,
  },
  {
    place: '台北凱撒大飯店',
    count: 217,
    pct_of_named_non_station: 0.041,
    pickup_count: 78,
    dropoff_count: 139,
  },
  {
    place: '兄弟大飯店',
    count: 216,
    pct_of_named_non_station: 0.04,
    pickup_count: 57,
    dropoff_count: 159,
  },
  {
    place: '大世界舞廳',
    count: 214,
    pct_of_named_non_station: 0.04,
    pickup_count: 7,
    dropoff_count: 207,
  },
  {
    place: '比漾廣場',
    count: 214,
    pct_of_named_non_station: 0.04,
    pickup_count: 41,
    dropoff_count: 173,
  },
  {
    place: 'ZARA統領店',
    count: 213,
    pct_of_named_non_station: 0.04,
    pickup_count: 102,
    dropoff_count: 111,
  },
  {
    place: '長庚醫院高雄分院',
    count: 212,
    pct_of_named_non_station: 0.04,
    pickup_count: 29,
    dropoff_count: 183,
  },
  {
    place: 'NOKE忠泰樂生活',
    count: 211,
    pct_of_named_non_station: 0.039,
    pickup_count: 83,
    dropoff_count: 128,
  },
  {
    place: '中山區行政中心',
    count: 207,
    pct_of_named_non_station: 0.039,
    pickup_count: 10,
    dropoff_count: 197,
  },
  {
    place: '義大大昌醫院',
    count: 206,
    pct_of_named_non_station: 0.038,
    pickup_count: 57,
    dropoff_count: 149,
  },
  {
    place: '內湖',
    count: 205,
    pct_of_named_non_station: 0.038,
    pickup_count: 205,
    dropoff_count: 0,
  },
  {
    place: '南門市場',
    count: 205,
    pct_of_named_non_station: 0.038,
    pickup_count: 24,
    dropoff_count: 181,
  },
  {
    place: '台中榮總 yoxi上車點 第一醫療大樓門口',
    count: 205,
    pct_of_named_non_station: 0.038,
    pickup_count: 118,
    dropoff_count: 87,
  },
  {
    place: '瀛海高中',
    count: 204,
    pct_of_named_non_station: 0.038,
    pickup_count: 203,
    dropoff_count: 1,
  },
  {
    place: '統聯客運朝馬站',
    count: 204,
    pct_of_named_non_station: 0.038,
    pickup_count: 10,
    dropoff_count: 194,
  },
  {
    place: '高雄醫學大學附設中和紀念醫院',
    count: 202,
    pct_of_named_non_station: 0.038,
    pickup_count: 12,
    dropoff_count: 190,
  },
  {
    place: '北醫附醫',
    count: 201,
    pct_of_named_non_station: 0.038,
    pickup_count: 6,
    dropoff_count: 195,
  },
  {
    place: '第一/第三門診出入口-yoxi上車點',
    count: 201,
    pct_of_named_non_station: 0.038,
    pickup_count: 128,
    dropoff_count: 73,
  },
  {
    place: '衛生福利部台北醫院',
    count: 199,
    pct_of_named_non_station: 0.037,
    pickup_count: 27,
    dropoff_count: 172,
  },
  {
    place: '中山醫大附設醫院大慶院區',
    count: 199,
    pct_of_named_non_station: 0.037,
    pickup_count: 21,
    dropoff_count: 178,
  },
  {
    place: 'DREAM PLAZA',
    count: 197,
    pct_of_named_non_station: 0.037,
    pickup_count: 49,
    dropoff_count: 148,
  },
  {
    place: '大倉久和大飯店',
    count: 197,
    pct_of_named_non_station: 0.037,
    pickup_count: 52,
    dropoff_count: 145,
  },
  {
    place: '南紡購物中心A1館',
    count: 197,
    pct_of_named_non_station: 0.037,
    pickup_count: 29,
    dropoff_count: 168,
  },
  {
    place: '台北南港展覽館1館',
    count: 196,
    pct_of_named_non_station: 0.037,
    pickup_count: 15,
    dropoff_count: 181,
  },
  {
    place: '福容大飯店高雄館',
    count: 196,
    pct_of_named_non_station: 0.037,
    pickup_count: 89,
    dropoff_count: 107,
  },
  {
    place: '新北市政府 yoxi上車點 正門招呼站',
    count: 196,
    pct_of_named_non_station: 0.037,
    pickup_count: 133,
    dropoff_count: 63,
  },
  {
    place: '錢櫃KTV台北南京店',
    count: 195,
    pct_of_named_non_station: 0.036,
    pickup_count: 93,
    dropoff_count: 102,
  },
  {
    place: '台北榮總',
    count: 194,
    pct_of_named_non_station: 0.036,
    pickup_count: 5,
    dropoff_count: 189,
  },
  {
    place: '全家',
    count: 194,
    pct_of_named_non_station: 0.036,
    pickup_count: 194,
    dropoff_count: 0,
  },
  {
    place: '承億酒店',
    count: 193,
    pct_of_named_non_station: 0.036,
    pickup_count: 73,
    dropoff_count: 120,
  },
  {
    place: 'ALTA NIGHTCLUB',
    count: 193,
    pct_of_named_non_station: 0.036,
    pickup_count: 39,
    dropoff_count: 154,
  },
  {
    place: '常用',
    count: 193,
    pct_of_named_non_station: 0.036,
    pickup_count: 193,
    dropoff_count: 0,
  },
  {
    place: '台北市兒童新樂園',
    count: 193,
    pct_of_named_non_station: 0.036,
    pickup_count: 51,
    dropoff_count: 142,
  },
  {
    place: '台北君品大酒店',
    count: 192,
    pct_of_named_non_station: 0.036,
    pickup_count: 113,
    dropoff_count: 79,
  },
  {
    place: '媽媽家',
    count: 191,
    pct_of_named_non_station: 0.036,
    pickup_count: 191,
    dropoff_count: 0,
  },
  {
    place: '美麗華 yoxi上車點 樂群三路出口',
    count: 190,
    pct_of_named_non_station: 0.035,
    pickup_count: 107,
    dropoff_count: 83,
  },
  {
    place: '家🏠',
    count: 190,
    pct_of_named_non_station: 0.035,
    pickup_count: 190,
    dropoff_count: 0,
  },
  {
    place: '南紡購物中心大門口yoxi上車點',
    count: 189,
    pct_of_named_non_station: 0.035,
    pickup_count: 174,
    dropoff_count: 15,
  },
  {
    place: '超級巨星自助式KTV高雄五福店',
    count: 187,
    pct_of_named_non_station: 0.035,
    pickup_count: 68,
    dropoff_count: 119,
  },
  {
    place: '格萊天漾大飯店',
    count: 187,
    pct_of_named_non_station: 0.035,
    pickup_count: 49,
    dropoff_count: 138,
  },
  {
    place: '香格里拉台北遠東國際大飯店',
    count: 186,
    pct_of_named_non_station: 0.035,
    pickup_count: 33,
    dropoff_count: 153,
  },
  {
    place: '茹曦酒店',
    count: 186,
    pct_of_named_non_station: 0.035,
    pickup_count: 59,
    dropoff_count: 127,
  },
  {
    place: '高雄中央公園英迪格酒店',
    count: 186,
    pct_of_named_non_station: 0.035,
    pickup_count: 73,
    dropoff_count: 113,
  },
  {
    place: '新光三越台北信義新天地A4館',
    count: 185,
    pct_of_named_non_station: 0.035,
    pickup_count: 26,
    dropoff_count: 159,
  },
  {
    place: '台北福華大飯店',
    count: 184,
    pct_of_named_non_station: 0.034,
    pickup_count: 37,
    dropoff_count: 147,
  },
  {
    place: '京站',
    count: 184,
    pct_of_named_non_station: 0.034,
    pickup_count: 23,
    dropoff_count: 161,
  },
  {
    place: '高雄巨蛋 yoxi上車點 博愛二路',
    count: 184,
    pct_of_named_non_station: 0.034,
    pickup_count: 167,
    dropoff_count: 17,
  },
  {
    place: '成功大學附設醫院-門診大樓',
    count: 183,
    pct_of_named_non_station: 0.034,
    pickup_count: 28,
    dropoff_count: 155,
  },
  {
    place: '聯合醫院中興院區',
    count: 183,
    pct_of_named_non_station: 0.034,
    pickup_count: 51,
    dropoff_count: 132,
  },
  {
    place: '煙波大飯店台南館',
    count: 182,
    pct_of_named_non_station: 0.034,
    pickup_count: 80,
    dropoff_count: 102,
  },
  {
    place: '圓山花博爭豔館 yoxi上車點(中山北路)',
    count: 182,
    pct_of_named_non_station: 0.034,
    pickup_count: 138,
    dropoff_count: 44,
  },
  {
    place: '台北101購物中心',
    count: 180,
    pct_of_named_non_station: 0.034,
    pickup_count: 13,
    dropoff_count: 167,
  },
  {
    place: '土城醫院',
    count: 180,
    pct_of_named_non_station: 0.034,
    pickup_count: 29,
    dropoff_count: 151,
  },
  {
    place: '統一時代百貨台北店',
    count: 179,
    pct_of_named_non_station: 0.033,
    pickup_count: 12,
    dropoff_count: 167,
  },
  {
    place: '外交部領事事務局',
    count: 176,
    pct_of_named_non_station: 0.033,
    pickup_count: 41,
    dropoff_count: 135,
  },
  {
    place: '台北榮總-中正樓',
    count: 175,
    pct_of_named_non_station: 0.033,
    pickup_count: 24,
    dropoff_count: 151,
  },
  {
    place: '勤美誠品綠園道',
    count: 174,
    pct_of_named_non_station: 0.033,
    pickup_count: 41,
    dropoff_count: 133,
  },
  {
    place: '台中李方艾美酒店',
    count: 174,
    pct_of_named_non_station: 0.033,
    pickup_count: 79,
    dropoff_count: 95,
  },
  {
    place: '書田泌尿科眼科診所',
    count: 174,
    pct_of_named_non_station: 0.033,
    pickup_count: 69,
    dropoff_count: 105,
  },
  {
    place: '萬豪酒店 yoxi上車點 中誠廣場-樂群二路出口',
    count: 174,
    pct_of_named_non_station: 0.033,
    pickup_count: 115,
    dropoff_count: 59,
  },
  {
    place: '錢櫃KTV高雄建興店',
    count: 171,
    pct_of_named_non_station: 0.032,
    pickup_count: 64,
    dropoff_count: 107,
  },
  {
    place: '松山慈祐宮',
    count: 170,
    pct_of_named_non_station: 0.032,
    pickup_count: 40,
    dropoff_count: 130,
  },
  {
    place: '台北榮總-第三門診',
    count: 170,
    pct_of_named_non_station: 0.032,
    pickup_count: 20,
    dropoff_count: 150,
  },
  {
    place: '台大醫院急診中心 yoxi上車點',
    count: 169,
    pct_of_named_non_station: 0.032,
    pickup_count: 89,
    dropoff_count: 80,
  },
  {
    place: '北醫',
    count: 168,
    pct_of_named_non_station: 0.031,
    pickup_count: 23,
    dropoff_count: 145,
  },
  {
    place: '錢櫃KTV新北永和店',
    count: 167,
    pct_of_named_non_station: 0.031,
    pickup_count: 57,
    dropoff_count: 110,
  },
  {
    place: '錢櫃KTV台南西門店',
    count: 167,
    pct_of_named_non_station: 0.031,
    pickup_count: 80,
    dropoff_count: 87,
  },
  {
    place: '國貿大樓',
    count: 167,
    pct_of_named_non_station: 0.031,
    pickup_count: 10,
    dropoff_count: 157,
  },
  {
    place: '台北龍山寺',
    count: 166,
    pct_of_named_non_station: 0.031,
    pickup_count: 11,
    dropoff_count: 155,
  },
  {
    place: '衛生福利部雙和醫院-第二醫療大樓',
    count: 164,
    pct_of_named_non_station: 0.031,
    pickup_count: 31,
    dropoff_count: 133,
  },
  {
    place: '美麗華百樂園購物中心',
    count: 163,
    pct_of_named_non_station: 0.03,
    pickup_count: 3,
    dropoff_count: 160,
  },
  {
    place: '松山文創園區',
    count: 163,
    pct_of_named_non_station: 0.03,
    pickup_count: 1,
    dropoff_count: 162,
  },
  {
    place: '超級巨星自助式KTV台中公園店',
    count: 163,
    pct_of_named_non_station: 0.03,
    pickup_count: 53,
    dropoff_count: 110,
  },
  {
    place: '中山醫院',
    count: 162,
    pct_of_named_non_station: 0.03,
    pickup_count: 34,
    dropoff_count: 128,
  },
  {
    place: '🏠',
    count: 162,
    pct_of_named_non_station: 0.03,
    pickup_count: 162,
    dropoff_count: 0,
  },
  {
    place: 'MITSUI SHOPPING PARK LALAPORT台中北館',
    count: 161,
    pct_of_named_non_station: 0.03,
    pickup_count: 11,
    dropoff_count: 150,
  },
  {
    place: '高雄洲際酒店',
    count: 160,
    pct_of_named_non_station: 0.03,
    pickup_count: 66,
    dropoff_count: 94,
  },
  {
    place: '高雄展覽館',
    count: 160,
    pct_of_named_non_station: 0.03,
    pickup_count: 41,
    dropoff_count: 119,
  },
  {
    place: '長庚醫院高雄分院-醫學大樓',
    count: 159,
    pct_of_named_non_station: 0.03,
    pickup_count: 42,
    dropoff_count: 117,
  },
  {
    place: '松山文創園區誠品生活 yoxi上車點',
    count: 158,
    pct_of_named_non_station: 0.03,
    pickup_count: 99,
    dropoff_count: 59,
  },
  {
    place: '大葉高島屋百貨公司',
    count: 157,
    pct_of_named_non_station: 0.029,
    pickup_count: 43,
    dropoff_count: 114,
  },
  {
    place: 'JR東日本大飯店台北',
    count: 157,
    pct_of_named_non_station: 0.029,
    pickup_count: 32,
    dropoff_count: 125,
  },
  {
    place: '耕莘醫院新店總院',
    count: 156,
    pct_of_named_non_station: 0.029,
    pickup_count: 22,
    dropoff_count: 134,
  },
  {
    place: '好市多內湖店',
    count: 155,
    pct_of_named_non_station: 0.029,
    pickup_count: 65,
    dropoff_count: 90,
  },
  {
    place: '西園醫院',
    count: 154,
    pct_of_named_non_station: 0.029,
    pickup_count: 38,
    dropoff_count: 116,
  },
  {
    place: '台南市立醫院',
    count: 152,
    pct_of_named_non_station: 0.028,
    pickup_count: 48,
    dropoff_count: 104,
  },
  {
    place: 'IKEA內湖店',
    count: 152,
    pct_of_named_non_station: 0.028,
    pickup_count: 34,
    dropoff_count: 118,
  },
  {
    place: '台北凱達大飯店',
    count: 151,
    pct_of_named_non_station: 0.028,
    pickup_count: 53,
    dropoff_count: 98,
  },
  {
    place: '北醫附醫-急診室',
    count: 151,
    pct_of_named_non_station: 0.028,
    pickup_count: 40,
    dropoff_count: 111,
  },
  {
    place: '三立電視股份有限公司',
    count: 151,
    pct_of_named_non_station: 0.028,
    pickup_count: 19,
    dropoff_count: 132,
  },
  {
    place: '台大醫院',
    count: 149,
    pct_of_named_non_station: 0.028,
    pickup_count: 9,
    dropoff_count: 140,
  },
  {
    place: '高雄榮總-門診大樓',
    count: 148,
    pct_of_named_non_station: 0.028,
    pickup_count: 43,
    dropoff_count: 105,
  },
  {
    place: '台大醫院兒童醫院 yoxi上車點',
    count: 147,
    pct_of_named_non_station: 0.027,
    pickup_count: 40,
    dropoff_count: 107,
  },
  {
    place: '台茂購物中心',
    count: 147,
    pct_of_named_non_station: 0.027,
    pickup_count: 43,
    dropoff_count: 104,
  },
  {
    place: '微笑時代',
    count: 146,
    pct_of_named_non_station: 0.027,
    pickup_count: 78,
    dropoff_count: 68,
  },
  {
    place: '711',
    count: 146,
    pct_of_named_non_station: 0.027,
    pickup_count: 146,
    dropoff_count: 0,
  },
  {
    place: '中山國小',
    count: 145,
    pct_of_named_non_station: 0.027,
    pickup_count: 112,
    dropoff_count: 33,
  },
  {
    place: '下班',
    count: 145,
    pct_of_named_non_station: 0.027,
    pickup_count: 145,
    dropoff_count: 0,
  },
  {
    place: '中菲電腦股份有限公司',
    count: 144,
    pct_of_named_non_station: 0.027,
    pickup_count: 86,
    dropoff_count: 58,
  },
  {
    place: '錢櫃KTV新北板橋店',
    count: 144,
    pct_of_named_non_station: 0.027,
    pickup_count: 45,
    dropoff_count: 99,
  },
  {
    place: '全家便利商店',
    count: 143,
    pct_of_named_non_station: 0.027,
    pickup_count: 114,
    dropoff_count: 29,
  },
  {
    place: '水木商旅',
    count: 143,
    pct_of_named_non_station: 0.027,
    pickup_count: 70,
    dropoff_count: 73,
  },
  {
    place: '政治大學',
    count: 143,
    pct_of_named_non_station: 0.027,
    pickup_count: 12,
    dropoff_count: 131,
  },
  {
    place: '中和紀念醫院-啟川大樓',
    count: 143,
    pct_of_named_non_station: 0.027,
    pickup_count: 27,
    dropoff_count: 116,
  },
  {
    place: 'ONCOR響艷都市會所信義店',
    count: 142,
    pct_of_named_non_station: 0.027,
    pickup_count: 72,
    dropoff_count: 70,
  },
  {
    place: '台中榮總-門診大樓',
    count: 142,
    pct_of_named_non_station: 0.027,
    pickup_count: 27,
    dropoff_count: 115,
  },
  {
    place: '和信醫院',
    count: 142,
    pct_of_named_non_station: 0.027,
    pickup_count: 18,
    dropoff_count: 124,
  },
  {
    place: '台南晶英酒店',
    count: 141,
    pct_of_named_non_station: 0.026,
    pickup_count: 44,
    dropoff_count: 97,
  },
  {
    place: '好樂迪KTV台中美村店',
    count: 141,
    pct_of_named_non_station: 0.026,
    pickup_count: 73,
    dropoff_count: 68,
  },
  {
    place: '好運來洲際宴展中心',
    count: 140,
    pct_of_named_non_station: 0.026,
    pickup_count: 59,
    dropoff_count: 81,
  },
  {
    place: '遠東百貨MEGA CITY板橋大遠百店',
    count: 139,
    pct_of_named_non_station: 0.026,
    pickup_count: 27,
    dropoff_count: 112,
  },
  {
    place: '博仁綜合醫院',
    count: 137,
    pct_of_named_non_station: 0.026,
    pickup_count: 21,
    dropoff_count: 116,
  },
  {
    place: '享溫馨庭園式自助KTV巨蛋店',
    count: 135,
    pct_of_named_non_station: 0.025,
    pickup_count: 52,
    dropoff_count: 83,
  },
  {
    place: '北醫附醫-第三醫療大樓',
    count: 135,
    pct_of_named_non_station: 0.025,
    pickup_count: 55,
    dropoff_count: 80,
  },
  {
    place: '饒河街觀光夜市',
    count: 134,
    pct_of_named_non_station: 0.025,
    pickup_count: 3,
    dropoff_count: 131,
  },
  {
    place: '新北地方法院',
    count: 134,
    pct_of_named_non_station: 0.025,
    pickup_count: 40,
    dropoff_count: 94,
  },
  {
    place: '台中家',
    count: 133,
    pct_of_named_non_station: 0.025,
    pickup_count: 133,
    dropoff_count: 0,
  },
  {
    place: '敦化國中',
    count: 133,
    pct_of_named_non_station: 0.025,
    pickup_count: 44,
    dropoff_count: 89,
  },
  {
    place: '台中林酒店',
    count: 132,
    pct_of_named_non_station: 0.025,
    pickup_count: 39,
    dropoff_count: 93,
  },
  {
    place: '工作室',
    count: 131,
    pct_of_named_non_station: 0.024,
    pickup_count: 131,
    dropoff_count: 0,
  },
  {
    place: '家樂福桂林店',
    count: 131,
    pct_of_named_non_station: 0.024,
    pickup_count: 38,
    dropoff_count: 93,
  },
  {
    place: '西門町',
    count: 131,
    pct_of_named_non_station: 0.024,
    pickup_count: 3,
    dropoff_count: 128,
  },
  {
    place: '新樓醫院台南總院',
    count: 131,
    pct_of_named_non_station: 0.024,
    pickup_count: 22,
    dropoff_count: 109,
  },
  {
    place: '香格里拉台南遠東國際大飯店',
    count: 131,
    pct_of_named_non_station: 0.024,
    pickup_count: 78,
    dropoff_count: 53,
  },
  {
    place: '臺北最High新年城-2024跨年晚會',
    count: 130,
    pct_of_named_non_station: 0.024,
    pickup_count: 0,
    dropoff_count: 130,
  },
  {
    place: '台灣高等法院民事庭大廈',
    count: 130,
    pct_of_named_non_station: 0.024,
    pickup_count: 28,
    dropoff_count: 102,
  },
  {
    place: '金錢豹酒店',
    count: 129,
    pct_of_named_non_station: 0.024,
    pickup_count: 9,
    dropoff_count: 120,
  },
  {
    place: '高雄榮總',
    count: 129,
    pct_of_named_non_station: 0.024,
    pickup_count: 9,
    dropoff_count: 120,
  },
  {
    place: '台大-綜合體育館',
    count: 129,
    pct_of_named_non_station: 0.024,
    pickup_count: 20,
    dropoff_count: 109,
  },
  {
    place: '忠孝國中',
    count: 129,
    pct_of_named_non_station: 0.024,
    pickup_count: 81,
    dropoff_count: 48,
  },
  {
    place: '聯合醫院松德院區',
    count: 129,
    pct_of_named_non_station: 0.024,
    pickup_count: 13,
    dropoff_count: 116,
  },
  {
    place: '台南應用科技大學',
    count: 129,
    pct_of_named_non_station: 0.024,
    pickup_count: 45,
    dropoff_count: 84,
  },
  {
    place: '環球世貿大樓',
    count: 129,
    pct_of_named_non_station: 0.024,
    pickup_count: 56,
    dropoff_count: 73,
  },
  {
    place: '好樂迪KTV V-MIX西屯店',
    count: 128,
    pct_of_named_non_station: 0.024,
    pickup_count: 67,
    dropoff_count: 61,
  },
  {
    place: '台北老爺大酒店',
    count: 128,
    pct_of_named_non_station: 0.024,
    pickup_count: 46,
    dropoff_count: 82,
  },
  {
    place: '天成飯店',
    count: 128,
    pct_of_named_non_station: 0.024,
    pickup_count: 81,
    dropoff_count: 47,
  },
  {
    place: '台北榮民總醫院',
    count: 128,
    pct_of_named_non_station: 0.024,
    pickup_count: 3,
    dropoff_count: 125,
  },
  {
    place: '奇博前門 yoxi上車點 二仁路車點',
    count: 128,
    pct_of_named_non_station: 0.024,
    pickup_count: 93,
    dropoff_count: 35,
  },
  {
    place: '廣三SOGO',
    count: 128,
    pct_of_named_non_station: 0.024,
    pickup_count: 29,
    dropoff_count: 99,
  },
  {
    place: '永樂市場',
    count: 128,
    pct_of_named_non_station: 0.024,
    pickup_count: 1,
    dropoff_count: 127,
  },
  {
    place: '君峰',
    count: 126,
    pct_of_named_non_station: 0.024,
    pickup_count: 70,
    dropoff_count: 56,
  },
  {
    place: '金華國中',
    count: 126,
    pct_of_named_non_station: 0.024,
    pickup_count: 22,
    dropoff_count: 104,
  },
  {
    place: '信義區松壽路20巷',
    count: 126,
    pct_of_named_non_station: 0.024,
    pickup_count: 106,
    dropoff_count: 20,
  },
  {
    place: '春大直CHUNPLACE',
    count: 126,
    pct_of_named_non_station: 0.024,
    pickup_count: 40,
    dropoff_count: 86,
  },
  {
    place: '台北地方法院',
    count: 126,
    pct_of_named_non_station: 0.024,
    pickup_count: 23,
    dropoff_count: 103,
  },
  {
    place: '信義區松仁路',
    count: 125,
    pct_of_named_non_station: 0.023,
    pickup_count: 122,
    dropoff_count: 3,
  },
  {
    place: '洲際棒球場 yoxi上車點 崇德十九路(文創園區旁)',
    count: 125,
    pct_of_named_non_station: 0.023,
    pickup_count: 115,
    dropoff_count: 10,
  },
  {
    place: '新莊典華館',
    count: 125,
    pct_of_named_non_station: 0.023,
    pickup_count: 34,
    dropoff_count: 91,
  },
  {
    place: '學校',
    count: 125,
    pct_of_named_non_station: 0.023,
    pickup_count: 125,
    dropoff_count: 0,
  },
  {
    place: '郭綜合醫院',
    count: 125,
    pct_of_named_non_station: 0.023,
    pickup_count: 33,
    dropoff_count: 92,
  },
  {
    place: '台北市懷愛館',
    count: 124,
    pct_of_named_non_station: 0.023,
    pickup_count: 10,
    dropoff_count: 114,
  },
  {
    place: 'HOME',
    count: 124,
    pct_of_named_non_station: 0.023,
    pickup_count: 124,
    dropoff_count: 0,
  },
  {
    place: '大立百貨A館',
    count: 124,
    pct_of_named_non_station: 0.023,
    pickup_count: 50,
    dropoff_count: 74,
  },
  {
    place: '花園夜市',
    count: 124,
    pct_of_named_non_station: 0.023,
    pickup_count: 10,
    dropoff_count: 114,
  },
  {
    place: '寧夏夜市',
    count: 124,
    pct_of_named_non_station: 0.023,
    pickup_count: 0,
    dropoff_count: 124,
  },
  {
    place: '凱撒帝苑',
    count: 123,
    pct_of_named_non_station: 0.023,
    pickup_count: 39,
    dropoff_count: 84,
  },
  {
    place: '中山醫大附設醫院-急診室',
    count: 122,
    pct_of_named_non_station: 0.023,
    pickup_count: 73,
    dropoff_count: 49,
  },
  {
    place: '城市商旅高雄真愛館',
    count: 122,
    pct_of_named_non_station: 0.023,
    pickup_count: 49,
    dropoff_count: 73,
  },
  {
    place: '誠品生活松菸店',
    count: 122,
    pct_of_named_non_station: 0.023,
    pickup_count: 9,
    dropoff_count: 113,
  },
  {
    place: '阮綜合醫院',
    count: 122,
    pct_of_named_non_station: 0.023,
    pickup_count: 12,
    dropoff_count: 110,
  },
  {
    place: '漢來飯店',
    count: 122,
    pct_of_named_non_station: 0.023,
    pickup_count: 19,
    dropoff_count: 103,
  },
  {
    place: '耕莘醫院永和分院',
    count: 122,
    pct_of_named_non_station: 0.023,
    pickup_count: 16,
    dropoff_count: 106,
  },
  {
    place: '景美女中',
    count: 121,
    pct_of_named_non_station: 0.023,
    pickup_count: 17,
    dropoff_count: 104,
  },
  {
    place: '賓士KTV高雄台鋁店',
    count: 121,
    pct_of_named_non_station: 0.023,
    pickup_count: 44,
    dropoff_count: 77,
  },
  {
    place: '錢櫃KTV台北敦南店',
    count: 121,
    pct_of_named_non_station: 0.023,
    pickup_count: 63,
    dropoff_count: 58,
  },
  {
    place: '寒軒國際大飯店',
    count: 120,
    pct_of_named_non_station: 0.022,
    pickup_count: 26,
    dropoff_count: 94,
  },
  {
    place: '高雄榮總-醫療大樓',
    count: 120,
    pct_of_named_non_station: 0.022,
    pickup_count: 42,
    dropoff_count: 78,
  },
  {
    place: '馬偕醫院台北院區',
    count: 120,
    pct_of_named_non_station: 0.022,
    pickup_count: 15,
    dropoff_count: 105,
  },
  {
    place: '衛生福利部桃園醫院',
    count: 119,
    pct_of_named_non_station: 0.022,
    pickup_count: 49,
    dropoff_count: 70,
  },
  {
    place: '高醫大',
    count: 119,
    pct_of_named_non_station: 0.022,
    pickup_count: 4,
    dropoff_count: 115,
  },
  {
    place: '行政院新莊聯合辦公大樓南棟',
    count: 118,
    pct_of_named_non_station: 0.022,
    pickup_count: 8,
    dropoff_count: 110,
  },
  {
    place: '阿嬤家',
    count: 118,
    pct_of_named_non_station: 0.022,
    pickup_count: 118,
    dropoff_count: 0,
  },
  {
    place: '奇美博物館',
    count: 118,
    pct_of_named_non_station: 0.022,
    pickup_count: 5,
    dropoff_count: 113,
  },
  {
    place: '高雄美國學校',
    count: 117,
    pct_of_named_non_station: 0.022,
    pickup_count: 11,
    dropoff_count: 106,
  },
  {
    place: '林新醫院',
    count: 117,
    pct_of_named_non_station: 0.022,
    pickup_count: 32,
    dropoff_count: 85,
  },
  {
    place: '遠東百貨TOP CITY台中大遠百店',
    count: 116,
    pct_of_named_non_station: 0.022,
    pickup_count: 6,
    dropoff_count: 110,
  },
  {
    place: '世貿一館',
    count: 116,
    pct_of_named_non_station: 0.022,
    pickup_count: 17,
    dropoff_count: 99,
  },
  {
    place: '聯合醫院和平院區',
    count: 115,
    pct_of_named_non_station: 0.021,
    pickup_count: 16,
    dropoff_count: 99,
  },
  {
    place: '大同區',
    count: 115,
    pct_of_named_non_station: 0.021,
    pickup_count: 114,
    dropoff_count: 1,
  },
  {
    place: '高醫大附設中和紀念醫院-急診室',
    count: 115,
    pct_of_named_non_station: 0.021,
    pickup_count: 35,
    dropoff_count: 80,
  },
  {
    place: '台北欣欣秀泰影城',
    count: 115,
    pct_of_named_non_station: 0.021,
    pickup_count: 9,
    dropoff_count: 106,
  },
  {
    place: '名媛名商會館',
    count: 115,
    pct_of_named_non_station: 0.021,
    pickup_count: 13,
    dropoff_count: 102,
  },
  {
    place: '都會HOTEL DUA',
    count: 115,
    pct_of_named_non_station: 0.021,
    pickup_count: 61,
    dropoff_count: 54,
  },
  {
    place: '美麗華 yoxi上車點 植福路出口',
    count: 115,
    pct_of_named_non_station: 0.021,
    pickup_count: 82,
    dropoff_count: 33,
  },
  {
    place: '台中商旅',
    count: 115,
    pct_of_named_non_station: 0.021,
    pickup_count: 93,
    dropoff_count: 22,
  },
  {
    place: 'A',
    count: 114,
    pct_of_named_non_station: 0.021,
    pickup_count: 114,
    dropoff_count: 0,
  },
  {
    place: '富邦A25',
    count: 114,
    pct_of_named_non_station: 0.021,
    pickup_count: 15,
    dropoff_count: 99,
  },
  {
    place: '上車地點',
    count: 114,
    pct_of_named_non_station: 0.021,
    pickup_count: 114,
    dropoff_count: 0,
  },
  {
    place: '統領百貨股份有限公司',
    count: 114,
    pct_of_named_non_station: 0.021,
    pickup_count: 15,
    dropoff_count: 99,
  },
  {
    place: '成功大學附設醫院-住院大樓',
    count: 114,
    pct_of_named_non_station: 0.021,
    pickup_count: 26,
    dropoff_count: 88,
  },
  {
    place: '宿舍',
    count: 114,
    pct_of_named_non_station: 0.021,
    pickup_count: 114,
    dropoff_count: 0,
  },
  {
    place: 'BELLAVITA寶麗廣場',
    count: 114,
    pct_of_named_non_station: 0.021,
    pickup_count: 12,
    dropoff_count: 102,
  },
  {
    place: 'IKEA台北城市店',
    count: 113,
    pct_of_named_non_station: 0.021,
    pickup_count: 74,
    dropoff_count: 39,
  },
  {
    place: '漢神洲際購物廣場 <預計2026年4月開幕>',
    count: 113,
    pct_of_named_non_station: 0.021,
    pickup_count: 23,
    dropoff_count: 90,
  },
  {
    place: '遠企購物中心',
    count: 113,
    pct_of_named_non_station: 0.021,
    pickup_count: 17,
    dropoff_count: 96,
  },
  {
    place: '高雄市政府四維行政中心',
    count: 113,
    pct_of_named_non_station: 0.021,
    pickup_count: 23,
    dropoff_count: 90,
  },
  {
    place: '永和',
    count: 113,
    pct_of_named_non_station: 0.021,
    pickup_count: 113,
    dropoff_count: 0,
  },
  {
    place: '夢時代購物中心 yoxi上車點 興發路',
    count: 113,
    pct_of_named_non_station: 0.021,
    pickup_count: 67,
    dropoff_count: 46,
  },
  {
    place: '高雄市立聯合醫院',
    count: 112,
    pct_of_named_non_station: 0.021,
    pickup_count: 13,
    dropoff_count: 99,
  },
  {
    place: '內湖高中',
    count: 112,
    pct_of_named_non_station: 0.021,
    pickup_count: 10,
    dropoff_count: 102,
  },
  {
    place: '延平中學',
    count: 112,
    pct_of_named_non_station: 0.021,
    pickup_count: 49,
    dropoff_count: 63,
  },
  {
    place: '我家',
    count: 111,
    pct_of_named_non_station: 0.021,
    pickup_count: 111,
    dropoff_count: 0,
  },
  {
    place: '新光三越高雄左營店本館',
    count: 111,
    pct_of_named_non_station: 0.021,
    pickup_count: 34,
    dropoff_count: 77,
  },
  {
    place: '大巨蛋秀泰影城',
    count: 111,
    pct_of_named_non_station: 0.021,
    pickup_count: 6,
    dropoff_count: 105,
  },
  {
    place: '全家便利商店新德明店',
    count: 111,
    pct_of_named_non_station: 0.021,
    pickup_count: 59,
    dropoff_count: 52,
  },
  {
    place: 'BARCODE TAIPEI',
    count: 111,
    pct_of_named_non_station: 0.021,
    pickup_count: 31,
    dropoff_count: 80,
  },
  {
    place: '台北南港展覽館2館',
    count: 110,
    pct_of_named_non_station: 0.021,
    pickup_count: 16,
    dropoff_count: 94,
  },
  {
    place: '松山區敦化北路',
    count: 110,
    pct_of_named_non_station: 0.021,
    pickup_count: 96,
    dropoff_count: 14,
  },
  {
    place: '美麗信花園酒店',
    count: 110,
    pct_of_named_non_station: 0.021,
    pickup_count: 23,
    dropoff_count: 87,
  },
  {
    place: '逢甲夜市',
    count: 110,
    pct_of_named_non_station: 0.021,
    pickup_count: 2,
    dropoff_count: 108,
  },
  {
    place: '統領大樓',
    count: 110,
    pct_of_named_non_station: 0.021,
    pickup_count: 18,
    dropoff_count: 92,
  },
  {
    place: '台中金典酒店',
    count: 109,
    pct_of_named_non_station: 0.02,
    pickup_count: 47,
    dropoff_count: 62,
  },
  {
    place: '台北地院',
    count: 108,
    pct_of_named_non_station: 0.02,
    pickup_count: 25,
    dropoff_count: 83,
  },
  {
    place: '板橋',
    count: 107,
    pct_of_named_non_station: 0.02,
    pickup_count: 97,
    dropoff_count: 10,
  },
  {
    place: '台南監獄',
    count: 107,
    pct_of_named_non_station: 0.02,
    pickup_count: 97,
    dropoff_count: 10,
  },
  {
    place: '台大醫院西址 yoxi上車點 公園路出口',
    count: 107,
    pct_of_named_non_station: 0.02,
    pickup_count: 4,
    dropoff_count: 103,
  },
  {
    place: '享溫馨庭園式自助KTV五福店',
    count: 107,
    pct_of_named_non_station: 0.02,
    pickup_count: 44,
    dropoff_count: 63,
  },
  {
    place: '金獅湖大酒店',
    count: 106,
    pct_of_named_non_station: 0.02,
    pickup_count: 29,
    dropoff_count: 77,
  },
  {
    place: 'TICC',
    count: 106,
    pct_of_named_non_station: 0.02,
    pickup_count: 15,
    dropoff_count: 91,
  },
  {
    place: '御廳苑',
    count: 106,
    pct_of_named_non_station: 0.02,
    pickup_count: 60,
    dropoff_count: 46,
  },
  {
    place: '台南大舞廳',
    count: 106,
    pct_of_named_non_station: 0.02,
    pickup_count: 26,
    dropoff_count: 80,
  },
  {
    place: '台北大巨蛋',
    count: 106,
    pct_of_named_non_station: 0.02,
    pickup_count: 0,
    dropoff_count: 106,
  },
  {
    place: '小窩',
    count: 106,
    pct_of_named_non_station: 0.02,
    pickup_count: 106,
    dropoff_count: 0,
  },
  {
    place: '長庚醫院高雄分院-復健大樓',
    count: 105,
    pct_of_named_non_station: 0.02,
    pickup_count: 35,
    dropoff_count: 70,
  },
  {
    place: '爸媽家',
    count: 105,
    pct_of_named_non_station: 0.02,
    pickup_count: 105,
    dropoff_count: 0,
  },
  {
    place: '台北士林萬麗酒店',
    count: 105,
    pct_of_named_non_station: 0.02,
    pickup_count: 34,
    dropoff_count: 71,
  },
  {
    place: '中正紀念堂 yoxi上車點 國家音樂廳(信義路)',
    count: 105,
    pct_of_named_non_station: 0.02,
    pickup_count: 45,
    dropoff_count: 60,
  },
  {
    place: '板橋慈惠宮',
    count: 104,
    pct_of_named_non_station: 0.019,
    pickup_count: 41,
    dropoff_count: 63,
  },
  {
    place: '板橋凱撒大飯店',
    count: 104,
    pct_of_named_non_station: 0.019,
    pickup_count: 50,
    dropoff_count: 54,
  },
  {
    place: '台北國泰醫院-第一分館',
    count: 104,
    pct_of_named_non_station: 0.019,
    pickup_count: 16,
    dropoff_count: 88,
  },
  {
    place: '台中勤美洲際酒店',
    count: 104,
    pct_of_named_non_station: 0.019,
    pickup_count: 37,
    dropoff_count: 67,
  },
  {
    place: '松山文創園區 yoxi上車點',
    count: 104,
    pct_of_named_non_station: 0.019,
    pickup_count: 10,
    dropoff_count: 94,
  },
  {
    place: '老新台菜十全店',
    count: 104,
    pct_of_named_non_station: 0.019,
    pickup_count: 35,
    dropoff_count: 69,
  },
  {
    place: '埔墘國小',
    count: 104,
    pct_of_named_non_station: 0.019,
    pickup_count: 3,
    dropoff_count: 101,
  },
  {
    place: '維多麗亞酒店',
    count: 104,
    pct_of_named_non_station: 0.019,
    pickup_count: 28,
    dropoff_count: 76,
  },
  {
    place: '台中榮總 yoxi上車點 第二醫療大樓門口',
    count: 104,
    pct_of_named_non_station: 0.019,
    pickup_count: 73,
    dropoff_count: 31,
  },
  {
    place: '禾馨民權婦幼診所',
    count: 103,
    pct_of_named_non_station: 0.019,
    pickup_count: 20,
    dropoff_count: 83,
  },
  {
    place: '信義運動中心',
    count: 103,
    pct_of_named_non_station: 0.019,
    pickup_count: 16,
    dropoff_count: 87,
  },
  {
    place: '新店慈濟醫院',
    count: 103,
    pct_of_named_non_station: 0.019,
    pickup_count: 12,
    dropoff_count: 91,
  },
  {
    place: '中國醫藥大學附設醫院-急重症中心大樓',
    count: 102,
    pct_of_named_non_station: 0.019,
    pickup_count: 32,
    dropoff_count: 70,
  },
  {
    place: '凱悅YES KTV高雄店',
    count: 102,
    pct_of_named_non_station: 0.019,
    pickup_count: 39,
    dropoff_count: 63,
  },
  {
    place: '高雄翰品酒店',
    count: 102,
    pct_of_named_non_station: 0.019,
    pickup_count: 35,
    dropoff_count: 67,
  },
  {
    place: '台大醫院-急診室',
    count: 101,
    pct_of_named_non_station: 0.019,
    pickup_count: 12,
    dropoff_count: 89,
  },
  {
    place: '新東南海鮮料理汀州店',
    count: 101,
    pct_of_named_non_station: 0.019,
    pickup_count: 30,
    dropoff_count: 71,
  },
  {
    place: '中山醫學大學附屬醫院 yoxi上車點 急診室門口(文心南路)',
    count: 101,
    pct_of_named_non_station: 0.019,
    pickup_count: 89,
    dropoff_count: 12,
  },
  {
    place: '新北市立殯儀館',
    count: 101,
    pct_of_named_non_station: 0.019,
    pickup_count: 5,
    dropoff_count: 96,
  },
  {
    place: '衛武營國家藝術文化中心',
    count: 101,
    pct_of_named_non_station: 0.019,
    pickup_count: 7,
    dropoff_count: 94,
  },
  {
    place: '榮耀世紀',
    count: 100,
    pct_of_named_non_station: 0.019,
    pickup_count: 55,
    dropoff_count: 45,
  },
  {
    place: 'SKM PARK',
    count: 100,
    pct_of_named_non_station: 0.019,
    pickup_count: 30,
    dropoff_count: 70,
  },
  {
    place: '聯合醫院仁愛院區',
    count: 100,
    pct_of_named_non_station: 0.019,
    pickup_count: 25,
    dropoff_count: 75,
  },
  {
    place: '出門',
    count: 100,
    pct_of_named_non_station: 0.019,
    pickup_count: 100,
    dropoff_count: 0,
  },
  {
    place: 'APPLE信義A13店',
    count: 100,
    pct_of_named_non_station: 0.019,
    pickup_count: 43,
    dropoff_count: 57,
  },
  {
    place: '台北醫學大學',
    count: 100,
    pct_of_named_non_station: 0.019,
    pickup_count: 13,
    dropoff_count: 87,
  },
  {
    place: '臨水宮',
    count: 100,
    pct_of_named_non_station: 0.019,
    pickup_count: 51,
    dropoff_count: 49,
  },
  {
    place: '道明中學',
    count: 100,
    pct_of_named_non_station: 0.019,
    pickup_count: 30,
    dropoff_count: 70,
  },
]

export const nonStationCategories: NonStationCategoryRow[] = [
  {
    category: '其他',
    count: 246122,
    pct_of_named_non_station: 45.974,
    pickup_count: 110275,
    dropoff_count: 135847,
  },
  {
    category: '住居',
    count: 96086,
    pct_of_named_non_station: 17.948,
    pickup_count: 95421,
    dropoff_count: 665,
  },
  {
    category: '醫療',
    count: 45936,
    pct_of_named_non_station: 8.581,
    pickup_count: 12601,
    dropoff_count: 33335,
  },
  {
    category: '辦公',
    count: 38310,
    pct_of_named_non_station: 7.156,
    pickup_count: 32630,
    dropoff_count: 5680,
  },
  {
    category: '餐飲旅宿',
    count: 37683,
    pct_of_named_non_station: 7.039,
    pickup_count: 13076,
    dropoff_count: 24607,
  },
  {
    category: '商業購物',
    count: 22190,
    pct_of_named_non_station: 4.145,
    pickup_count: 6738,
    dropoff_count: 15452,
  },
  {
    category: '便利商店',
    count: 14383,
    pct_of_named_non_station: 2.687,
    pickup_count: 8872,
    dropoff_count: 5511,
  },
  {
    category: '公共服務',
    count: 11913,
    pct_of_named_non_station: 2.225,
    pickup_count: 4551,
    dropoff_count: 7362,
  },
  {
    category: '教育',
    count: 10308,
    pct_of_named_non_station: 1.925,
    pickup_count: 3199,
    dropoff_count: 7109,
  },
  {
    category: '社區住宅',
    count: 6536,
    pct_of_named_non_station: 1.221,
    pickup_count: 2052,
    dropoff_count: 4484,
  },
  {
    category: '休閒運動',
    count: 5881,
    pct_of_named_non_station: 1.099,
    pickup_count: 1764,
    dropoff_count: 4117,
  },
]
